version: "2"
services:
  nginx:
    build: nginx
    image: habitissimo/myaas-nginx
    ports:
      - 80:80
    links:
      - myaas
      - gui

  myaas:
    build: .
    image: habitissimo/myaas
    environment:
      - DEBUG=1
      - TZ=Europe/Madrid
      - MYAAS_HOSTNAME=127.0.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/code/
      - /opt/myaas:/myaas


  gui:
    build: gui
    image: habitissimo/myaas-gui
